language: ruby
cache: bundler
sudo: false

before_install: ./travis/before_install
bundler_args: --without=development

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

rvm: 2.4.4
matrix:
  include:
    - env: VAGRANT_VERSION=v2.2.2
    - env: VAGRANT_VERSION=v2.0.4
    - env:
        - VAGRANT_VERSION=v1.8.7
        - BUNDLER_VERSION=1.12.5
      rvm: 2.2.5
    - env: VAGRANT_VERSION=master
  allow_failures:
    - env: VAGRANT_VERSION=master
